version: '3.9'
services:
  webserver:
    container_name: PHP-webServer
    build:
      context: .
      dockerfile: ./apachephp/Dockerfile
    volumes:
      - './html:/var/www/html'
    ports:
      - 8080:80