services:
  webserver:
    container_name: apache-php-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - './www:/var/www'
      # - './html/whiteacorn:/var/www/whiteacorn'
      # - './html/iracoon:/var/www/iracoon'
      # - './html/phpmyadmin:/var/www/phpmyadmin'
      # - './html/test_host:/var/www/testhost'

      # - '$HOME/Sites:/var/www'

      - '$HOME/Sites/whiteacorn:/var/www/whiteacorn'
      - '$HOME/Sites/iracoon:/var/www/iracoon'
      - '$HOME/Sites/phpmyadmin:/var/www/phpmyadmin'
      - './www/testhost:/var/www/testhost'
      - './www:/var/www'
      - '$HOME/MyPhpPackages/database-package:/var/www/database-package'
      - ./phpcli:/var/www/php
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql/mysql-server
    container_name: wa-mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "wara2074"
      # MYSQL_DATABASE: "whiteacorn"
      # MYSQL_DATABASE: "database_package_test_db"
      MYSQL_USER: wauser
      MYSQL_PASSWORD: wara2074
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - dbData:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
volumes:
#   app:
  dbData:
